version = 0.1
default-task = 'build'

extensions = ['chomp@0.1:swc', 'chomp@0.1:jspm']

[[task]]
name = 'build'
deps = ['build:js', 'html']

[[task]]
name = 'build:js'
template = 'swc'
target = 'lib/##.js'
deps = ['src/##.ts']
[task.template-options]
config-file = '.swcrc'

[[task]]
name = 'html'
target = 'index.html'
deps = ['index.html', 'lib/**/*.js']
template = 'jspm'
[task.template-options]
env = ['production', 'browser', 'module']
preload = true
integrity = true