name: '@saeon/parallel-cmds'
description: 'Run cmds in parallel'
inputs:
  cores:
    description: Number of available cores to use
    required: false
    default: ''
  cmds:  # id of input
    description: 'List of commands to execute'
    required: true
    default: |
      'echo "No commands specified"'
outputs:
  time: # id of output
    description: 'Time of completion'
runs:
  using: 'node16'
  main: 'index.js'