version = 0.1

[[task]]
name = 'init'
run = '''
  husky install
  git config --local include.path ../.gitconfig
'''

[[task]]
name = 'doc'
run = '''
  doctoc README.md
'''

[[task]]
name = 'prettier'
run = 'echo todo'