version = 0.1

[[task]]
name = 'init'
run = '''
  npm install
  husky install
  chmod +x .husky/pre-commit
  git config --local include.path ../.gitconfig
'''

[[task]]
name = 'doc'
run = '''
  doctoc *.md
  doctoc toolkit/*.md
  doctoc models/**/*.md
  doctoc models/**/**/*.md
  doctoc docker/**/*.md
'''