version = 0.1

[[task]]
name = 'init'
run = '''
  npm install
  husky install
  chmod +x .husky/pre-commit
  git config --local include.path ../.gitconfig
'''

[[task]]
name = 'doc'
run = '''
  doctoc README.md
'''

[[task]]
name = 'prettier'
run = 'prettier --write "./**/*.@(js|jsx|json|mjs|cjs|graphql|yml)"'

[[task]]
name = 'prettier:quick'
run = 'pretty-quick'