version: '3.8'

networks:
  somisana_next:
    name: somisana_next
    driver: overlay
    attachable: true

services:
  node:
    image: $DOCKER_IMAGE
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
    environment:
      ALLOWED_ORIGINS: https://somisana.dvn
      MONGO_HOST: $MONGO_HOST
      MONGO_DB: $MONGO_DB
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
    ports:
      - 6007:3000
    networks:
      - somisana_next

  pg_tileserv:
    image: pramsey/pg_tileserv:20220623
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: '2'
          memory: 1G
    environment:
      DATABASE_URL: $PG_DATABASE_URL
    ports:
      - 6009:7800
    networks:
      - somisana_next
