name: somisana
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.10.6
  - numpy
  - xarray
  - cython
  - netcdf4
  - pymongo
  - environs
  - requests
  - pathlib
  - pyyaml
  - zarr
  - pandas
  - natsort
  - matplotlib
  - aiohttp
  - siphon
  - dask
  - aiofiles
  - kerchunk
  - fsspec
  - h5py
  - spyder=5.3.2
  - psutil
  - scipy
  - asyncpg
  - pydap
  - lxml
  - pytest
  - pip
  - pip:
      - psycopg==3.1.8
      - psycopg-pool==3.1.6
      - cchardet
      - copernicus-marine-client>=0.10.0<0.11.0
