version: '3.8'

volumes:
   data:
   settings:

networks:
  geoserver:
    name: geoserver
    driver: overlay
    attachable: true

services:
  geoserver:
    image: kartoza/geoserver:2.20.4
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: '4'
          memory: 4G
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_USER=$GEOSERVER_ADMIN_USER
      - GEOSERVER_ADMIN_PASSWORD=$GEOSERVER_ADMIN_PASSWORD
      - JAVA_OPTS="-DALLOW_ENV_PARAMETRIZATION=true"
      - PROXY_BASE_URL=https://maps.somisana.ac.za/geoserver
    volumes:
      - data:/opt/geoserver/data_dir
      - settings:/settings
    ports:
      - 7009:8080
    networks:
      - geoserver