version: '3.8'

networks:
  pg_tileserv:
    name: pg_tileserv
    driver: overlay
    attachable: true

services:
  pg_tileserv:
    image: pramsey/pg_tileserv:20220623
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: '4'
          memory: 2G
    environment:
      - DATABASE_URL:$DATABASE_URL
    ports:
      - 7009:7800
    networks:
      - pg_tileserv