version: '3.9'

networks:
  somisana_stable:
    name: somisana_stable
    driver: overlay
    attachable: true

services:
  node:
    image: $DOCKER_IMAGE
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.apps == true
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 15s
    environment:
      ALLOWED_ORIGINS: https://somisana.ac.za,https://somisana.saeon.ac.za
      ODP_SSO_CLIENT_SECRET: $ODP_SSO_CLIENT_SECRET
      HOSTNAME: $HOSTNAME
      MONGO_HOST: $MONGO_HOST
      MONGO_DB: $MONGO_DB
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      PG_HOST: $PG_HOST
      PG_PORT: $PG_PORT
      PG_DB: $PG_DB
      PG_USERNAME: $PG_USERNAME
      PG_PASSWORD: $PG_PASSWORD
    ports:
      - 7008:3000
    networks:
      - somisana_stable

  pg_tileserv:
    image: pramsey/pg_tileserv:20230210
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.apps == true
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: '2'
          memory: 1G
    environment:
      DATABASE_URL: $PG_DATABASE_URL
    ports:
      - 7009:7800
    networks:
      - somisana_stable

  pg_featureserv:
    image: pramsey/pg_featureserv:20230120
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.apps == true
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: '2'
          memory: 1G
    environment:
      DATABASE_URL: $PG_DATABASE_URL
    ports:
      - 7011:9000
    networks:
      - somisana_stable
