name: algoa-bay-forecast

on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - next

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_algoa-bay-post-processing
  POSTGIS_USERNAME: TODO
  POSTGIS_PASSWORD: TODO
  BRANCH_REF: next

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: post-processing/algoa-bay-forecast
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  exe:
    needs: [build]
    runs-on: github-runner.saeon.int
    steps:
      - name: Execute python script
        run: >-
          docker run \
            -e POSTGIS_USERNAME=${{ env.POSTGIS_USERNAME }} \
            -e POSTGIS_PASSWORD=${{ env.POSTGIS_PASSWORD }} \
            --rm \
            ${{ needs.build.outputs.image }}
