name: Build Python Docker image (with GDAL)

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_geopython

jobs:
  # Dynamically set the branch ref to the currently executing branch
  branch-ref:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.BRANCH_REF.outputs.value }}
    steps:
    - name: Set the BRANCH_REF
      id: BRANCH_REF
      run: echo "value=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

  build:
    needs: [branch-ref]
    runs-on: ubuntu-latest
    env:
      BRANCH_REF: ${{ needs.branch-ref.outputs.value }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: docker/geopython
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}