name: Debug

on:
  workflow_dispatch:

jobs:
  debugger:
    runs-on: somisana
    steps:
      - name: Source ~/.bashrc (for NVM - required for non-interactive shells)
        run: |
          echo $PATH
          pwd
          source ~/.bashrc
          node --version
          nvm use 19.6.0