name: Debug

on:
  workflow_dispatch:

env:
  TEST: 'HELLO WORLD'

jobs:
  debugger:
    runs-on: ubuntu-latest
    steps:
      - name: Debug 1
        id: 'lowercase'
        run: |
          T=$(echo $TEST | tr '[:upper:]' '[:lower:]')
          echo "image_name=$T" >> $GITHUB_OUTPUT
      - name: Debug 2
        run: |
          echo ${{ steps.lowercase.outputs.image_name }}
