name: Debug

on:
  workflow_dispatch:

jobs:

  debugger:
    runs-on: somisana
    steps:
      - name: Archive raw CROCO output (hindcast / forecast)
        run: |
          curl \
            --silent \
            --keepalive-time 2400 \
            -X PUT \
            -H "Content-Type: application/octet-stream" \
            -H "Authorization: ${{ secrets.MNEMOSYNE_TOKEN }}" \
            -T /home/runner/somisana/algoa-bay-forecast/stable/20230815/croco/forecast/hourly-avg-20230815-archive.nc \
            https://mnemosyne.somisana.ac.za/somisana/algoa-bay/5-day-forecast/202308/20230815_hourly_avg_fcst.nc;
