name: build@saeon/geopython

on:
  push:
    tags:        
      - geopython.v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_geopython
  BRANCH_REF: stable

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Setup tag name
        run: |
          echo "hi"
          echo "TAG=$(echo refs/tags/geopython.v0.0.4 | sed $"s/refs\/tags\/geopython.v//g")" >> $GITHUB_ENV
          echo "${{ github.ref }}"
          echo $GITHUB_SHA_SHORT
      # - name: Checkout source code
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ env.BRANCH_REF }}

      # - name: Log in to the Container registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     tags: |
      #       type=raw,value=latest
      #       type=ref,event=tag
      #       type=sha

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: docker/geopython
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}