name: run_somisana

on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - next

env:
  IMAGE_NAME: ghcr.io/saeon/somisana_python-scripts:0.0.4
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_PORT: ${{ secrets.PG_PORT_NEXT }}
  PG_USERNAME: ${{ secrets.PG_USERNAME }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  MONGO_HOST: ${{ secrets.MONGO_HOST_NEXT }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  exe:
    runs-on: github-runner.saeon.int
    steps:
      - name: Algoa Bay forecast (post processing) 
        run: >-
          docker run \
            --rm \
            -e PG_HOST=${{ env.PG_HOST }} \
            -e PG_PORT=${{ env.PG_PORT }} \
            -e PG_USERNAME=${{ env.PG_USERNAME }} \
            -e PG_PASSWORD=${{ env.PG_PASSWORD }} \
            -e MONGO_HOST=${{ env.MONGO_HOST }} \
            -e MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            -e MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
            -e SCRIPT_NAME=popr_algoa-bay-forecast \
            ${{ env.IMAGE_NAME }}
