name: build@saeon/somisana_python-scripts

on:
  push:
    tags:        
      - python-scripts.v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_python-scripts
  BRANCH_REF: stable

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=match,pattern=python-scripts\.v(.*),group=1,priority=1000
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/python-scripts/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}