name: Run OpenDrift

on:
  workflow_dispatch:
    inputs:
      run_model:
        description: 'run the model'
        required: true
        type: boolean
        default: true
      plotting:
        description: 'do the plots'
        required: true
        type: boolean
        default: true

# Many of the env variables reference the current branch,
# which is set dynamically in the branch-ref job below
# So the env variables are mostly set in the envs job below the branch-ref job
env:
  REGISTRY: ghcr.io

jobs:
  # Dynamically set the branch ref to the currently executing branch
  branch-ref:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.BRANCH_REF.outputs.value }}
    steps:
      - name: Set the BRANCH_REF
        id: BRANCH_REF
        run: |
          echo "value=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

  # Set the environment variables using the current branch reference
  envs:
    needs: [branch-ref]
    runs-on: ubuntu-latest
    outputs:
      BRANCH_REF: ${{ needs.branch-ref.outputs.value }}
      TOOLKIT_IMAGE: ${{ steps.ENVS.outputs.TOOLKIT_IMAGE }}
      OPENDRIFT_IMAGE: ${{ steps.ENVS.outputs.OPENDRIFT_IMAGE }}
      CONFIG_NAME: ${{ steps.ENVS.outputs.CONFIG_NAME }}
      CROCO_RUN_DATE: ${{ steps.ENVS.outputs.CROCO_RUN_DATE }}
      RUN_DIR: ${{ steps.ENVS.outputs.RUN_DIR }}
    steps:
      - name: Check out source code
        uses: actions/checkout@main
        with:
          ref: ${{ needs.branch-ref.outputs.value }}
      - name: configuration name
        id: config_name
        run: |
          # Use grep to find the line where the variable is defined
          line=$(grep -w config_name opendrift/oil/config_oil.py)
          # Use awk to extract the value of the variable from the line (thanks chatgpt)
          echo "value=$(echo "$line" | awk -F "=" '{print $2}' | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT
      - name: run date 
        id: run_date
        run: |
          # Use grep to find the line where the variable is defined
          line=$(grep -w croco_run_date opendrift/oil/config_oil.py)
          # Use awk to extract the value of the variable from the line (thanks chatgpt)
          echo "value=$(echo "$line" | awk -F "=" '{print $2}' | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT
      - name: Set envs
        id: ENVS
        run: |
          # intentionally use the latest stable toolkit image, not the branch we're running opendrift on
          echo "TOOLKIT_IMAGE=ghcr.io/saeon/somisana_toolkit_stable:latest" >> $GITHUB_OUTPUT
          echo "OPENDRIFT_IMAGE=${{ github.repository }}_opendrift_${{ needs.branch-ref.outputs.value }}" >> $GITHUB_OUTPUT
          echo "CONFIG_NAME=${{ steps.config_name.outputs.value }}" >> $GITHUB_OUTPUT
          echo "CROCO_RUN_DATE=${{ steps.run_date.outputs.value }}" >> $GITHUB_OUTPUT
          echo "RUN_DIR=/home/runner/somisana/opendrift/${{ steps.run_date.outputs.value }}/${{ steps.config_name.outputs.value }}" >> $GITHUB_OUTPUT

  setup-run-dir:
    needs: [envs]
    runs-on: somisana
    if: ${{ github.event.inputs.run_model }}
    env:
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      OPENDRIFT_IMAGE: ${{ needs.envs.outputs.OPENDRIFT_IMAGE }}
      RUN_DIR: ${{ needs.envs.outputs.RUN_DIR }}
    steps:
      - name: Clean /home/runner/somisana/opendrift/
        continue-on-error: true # Allow for the case where there are no folders in directory
        run: >-
          find \
            /home/runner/somisana/opendrift/* \
            -maxdepth 0 \
            -type d \
            -ctime +5 \
            -exec \
              rm \
                -rf {} \;
      - name: Create ${{ env.RUN_DIR }} directory
        run: |
          rm -rf ${{ env.RUN_DIR }}
          mkdir -p ${{ env.RUN_DIR }}
          chown -R :runner ${{ env.RUN_DIR }}
          chmod -R 774 ${{ env.RUN_DIR }}

  build-image:
    needs: [envs]
    runs-on: ubuntu-latest
    env:
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      OPENDRIFT_IMAGE: ${{ needs.envs.outputs.OPENDRIFT_IMAGE }}
      SHA: sha-${{ github.sha }}
    outputs:
      image: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.image_name }}
    steps:
      - name: Get image name lowercase
        id: 'lowercase'
        run: |
          IMAGE_NAME_LOWER=$(echo $OPENDRIFT_IMAGE | tr '[:upper:]' '[:lower:]')
          echo "image_name=$IMAGE_NAME_LOWER" >> $GITHUB_OUTPUT
      - name: Check out source code
        uses: actions/checkout@main 
        with:
          ref: ${{ env.BRANCH_REF }}
      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if image with sha tag already exists
        id: check-image
        run: |
          set -e
          SHA_IMAGE=$(docker images -q ${REGISTRY}/${{ steps.lowercase.outputs.image_name }}:${SHA} || true)
          if [ -z "$SHA_IMAGE" ]; then
            echo "image_exists=false" >> $GITHUB_OUTPUT
          else
            echo "image_exists=true" >> $GITHUB_OUTPUT
          fi
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.OPENDRIFT_IMAGE }}
          tags: |
            latest
            ${{ env.SHA }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: opendrift
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  run-oil:
    needs: [build-image, envs]
    runs-on: somisana
    if: ${{ github.event.inputs.run_model }}
    env:
      SHA: sha-${{ github.sha }}
    steps:
      - name: run the model
        run: >-
          docker run \
            --rm \
            -v /home/runner/somisana/:/tmp/ \
            --entrypoint /bin/bash \
            ${{ needs.build-image.outputs.image }}:${{ env.SHA }} \
            -c "python /somisana/oil/run_oil.py"

  plot-oil:
    needs: [build-image, envs, run-oil]
    runs-on: somisana
    if: ${{ github.event.inputs.plotting }}
    env:
      SHA: sha-${{ github.sha }}
    steps:
      - name: run the model
        run: >-
          docker run \
            --rm \
            -v /home/runner/somisana/:/tmp/ \
            --entrypoint /bin/bash \
            ${{ needs.build-image.outputs.image }}:${{ env.SHA }} \
            -c "python /somisana/oil/plot_oil.py"


  # Archive output
  archive-data:
    needs: [envs, run-oil]
    runs-on: somisana
    env:
      TOOLKIT_IMAGE: ${{ needs.envs.outputs.TOOLKIT_IMAGE }}
      CONFIG_NAME: ${{ needs.envs.outputs.CONFIG_NAME }}
      CROCO_RUN_DATE: ${{ needs.envs.outputs.CROCO_RUN_DATE }}
    steps:
      - name: Load $PATH
        run: |
          source ~/.bashrc
      - name: Kerchunk NetCDF output
        continue-on-error: true
        run: |
          docker run \
            --rm \
            -v /home/runner/somisana/:/tmp/ \
            ${{ env.TOOLKIT_IMAGE }} \
              kerchunk \
                run \
                  --inputs /home/runner/somisana/opendrift/${{ env.CROCO_RUN_DATE }}/${{ env.CONFIG_NAME }}/trajectories.nc \
                  --output /home/runner/somisana/opendrift/${{ env.CROCO_RUN_DATE }}/${{ env.CONFIG_NAME }}/trajectories.kerchunk.json
      - name: Archive the OpenDrift output
        continue-on-error: false
        run: |
          base_dir=/home/runner/somisana/opendrift/${{ env.CROCO_RUN_DATE }}/${{ env.CONFIG_NAME }}
          find "$base_dir" -type f -exec sh -c '
              f="$1"
              base="$2"
              url=https://mnemosyne.somisana.ac.za/somisana/opendrift/${{ env.CROCO_RUN_DATE }}/${{ env.CONFIG_NAME }}/${f#$base/}
              curl \
              --silent \
              --keepalive-time 2400 \
              -X POST \
              -H "Authorization: ${{ secrets.MNEMOSYNE_TOKEN }}" \
              --create-dirs \
              -T "$f" \
              $url' sh {} "$base_dir" \;

