name: Test local action

on: 
  workflow_dispatch:

env:
  BRANCH_REF: next

jobs:
  hello_world_job:
    runs-on: github-runner.saeon.int
    name: A job to say hello
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_REF }}
      - name: Install node_modules for action
        run: npm ci --only production --prefix .github/actions/hello-world/
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/hello-world
        with:
          who-to-greet: 'SOMISANA locally defined action'
      - name: Get the output time
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1
          retry_wait_seconds: 1 # Wait 10 minutes and try again
          max_attempts: 3
          retry_on: any
          warning_on_retry: true
          shell: bash
          continue_on_error: false
          command: >- 
            echo "The time was ${{ steps.hello.outputs.time }}" \
              && asdad