name: Actions tester

on: 
  workflow_dispatch:

env:
  BRANCH_REF: next

jobs:
  hello_world_job:
    runs-on: github-runner.saeon.int
    name: Run parallel cmds
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_REF }}
      # - name: Install node_modules for action
      #   run: |
      #     source ~/.bashrc
      #     nvm use 16.14.2
      #     npm ci --only production --prefix .github/actions/parallel-cmds/
      - name: Hello world action step
        id: parallel-cmds
        uses: ./.github/actions/parallel-cmds
        with:
          cmds: |
            echo hi1
            echo hi2
            echo hi3