name: deploy-web@next

on:
  push:
    tags:
      - web-dev.v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_web-dev
  BRANCH_REF: next

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=web-dev\.v(.*),group=1,priority=1000
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
