name: deploy-web@next

on:
  push:
    branches:
      - next

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_web
  BRANCH_REF: next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test workflow
        run: |
          echo TODO
