version = 0.1
default-task = 'start'

extensions = ['chomp@0.1:prettier']

[[task]]
name = 'build'
deps = [
  'clear-cache',
  'rollup:client',
  'rollup:server',
  'jspm:client',
  'jspm:node',
  'copy-static-files'
]
serial = true

[[task]]
name = 'start'
env = { TZ='UTC', NODE_ENV='development' }
serial = true
deps = [
  'client',
  'rollup:server',
  'node.importmap'
]
run = """
node \
  --loader ./loaders/http/index.js \
  --loader @node-loader/import-maps \
  --loader ./loaders/std-lib-imports/index.js \
  --trace-warnings \
  server
"""
  
  

[[task]]
name = 'client'
serial = true
deps = [
  'rollup:client',
  'jspm:client',
  'copy-static-files',
]

[[task]]
name = 'copy-static-files'
run = '''
cp -r public/* .client/
'''

[[task]]
name = 'rollup:server'
deps = [
  'server/**/*',
  'loaders/**/*',
  'ssr/**/*'
]
run = 'rollup -c rollup/server.config.js'

[[task]]
name = 'jspm:node'
targets = ['node.importmap']
deps = [
    'index.importmap.js'
]
run = "node jspm-node.js"

[[task]]
name = 'jspm:client'
targets = ['.client/#.html']
deps = [
    'client/html/#.html'
]
run = "node jspm-client.js"

[[task]]
name = "rollup:client"
deps = [
  'client/**/*',
  'common/**/*'
]
run = 'rollup --config rollup/client.config.js'

[[task]]
name = 'prettier'
deps = ['prettier:server', 'prettier:client', 'prettier:other']

[[task]]
name = 'prettier:client'
template = 'prettier'
[task.template-options]
ignore-path = '../.prettierignore'
loglevel = 'warn'
files = 'client/**/*.@(js|jsx|json|mjs|cjs|graphql|html|yml|ts|tsx|css) common/**/*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)'

[[task]]
name = 'prettier:server'
template = 'prettier'
[task.template-options]
ignore-path = '../.prettierignore'
loglevel = 'warn'
files = 'cli/**/*.js loaders/**/*.js server/**/*.@(js|json|geojson|cjs|mjs|graphql) ssr/**/*.@(js|json|geojson|cjs|mjs|graphql|ts|tsx|jsx)'

[[task]]
name = 'prettier:other'
template = 'prettier'
[task.template-options]
ignore-path = '../.prettierignore'
loglevel = 'warn'
files = 'rollup/**/*.js ./*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)'


[[task]]
name = 'reset'
deps = [
  'clear-cache',
  'clear-jspm-cache'
]
run = """
rm -rf node_modules
find . \
  -name node_modules \
  -type d \
  -exec rm -rv {} + \
    && find . \
      -name package-lock.json \
      -type f \
      -delete
"""

[[task]]
name = 'clear-cache'
run = '''
rimraf node.importmap
rimraf .client
rimraf .ssr
'''

[[task]]
name = 'clear-jspm-cache'
engine = 'node'
run = """
import { clearCache } from '@jspm/generator';
clearCache();
"""