version = 0.1
default-task = 'start'

extensions = ['chomp@0.1:jspm']

[[task]]
name = 'start'
serial = true
deps = ['webpack', 'server',]

[[task]]
name = 'server'
env = { TZ='UTC' }
run = """
nodemon --watch server/ --exec \
  'prettier --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql)" && \
   node --trace-warnings --loader ./loaders/geojson.js --experimental-json-modules server'
"""


[[task]]
name = 'webpack'
deps = ["build:js"]
run = """
rimraf server/ssr/dist
webpack --config webpack/index.cjs
"""

[[task]]
name = 'build:js'
dep = 'clients/##'
run = """
swc clients -d .clients_build
"""



[[task]]
name = 'jspm'
dep = 'server/ssr/dist/#.html'
target = 'server/ssr/dist/#-done.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'production', 'module']
preload = true
integrity = false

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = """
ncu -u
npm install
"""

