version = 0.1
default-task = 'start'

[[task]]
name = 'build:deployment'
deps = [
  'clear-cache',
  'rollup:client',
  'rollup:ssr',
  'jspm:client',
  'jspm:node',
  'copy-static-files'
]
serial = true

[[task]]
name = 'start'
deps = [
    '.cache',
    '.cache/*.html',
    'copy-static-files',
    'server',
]
serial = true

#############################
#############################
#############################

[[task]]
name = 'copy-static-files'
run = '''
cp -r public/* .cache/
'''

[[task]]
name = 'server'
env = { TZ='UTC', NODE_LOADER_CONFIG='loaders/config.js' }
serial = true
deps = [
  'rollup:ssr',
  'node.importmap',
  'server/**/*.js',
]
run = """
prettier \
  --loglevel warn \
  --cache \
  --cache-strategy metadata \
  --ignore-path ../.prettierignore \
  --write "ssr/**/*.@(js|json|geojson|cjs|mjs|graphql|ts|tsx|jsx)" \
  --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql|ts|tsx|jsx)" \
  --write "loaders/**/*.js" && \
    node \
      --trace-warnings \
      --loader @node-loader/core \
      server
"""

[[task]]
name = 'rollup:ssr'
deps = ['ssr/**/*.jsx']
env = { TZ='UTC' }
run = 'rollup -c rollup/server.config.js'

############################# 
#############################
#############################

# Create an import map for node
[[task]]
name = 'jspm:node'
targets = ['node.importmap']
deps = [
    'index.importmap.js',
    '.cache'
]
invalidation = 'always'
run = "node jspm-node.js"

# Transpile HTML + js => HTML / import map
[[task]]
name = 'jspm:client'
targets = ['.cache/#.html']
deps = [
    'client/html/#.html',
    '.cache'
]
invalidation = 'always'
run = "node jspm-client.js"

[[task]]
name = "rollup:client"
target = '.cache'
env = { TZ='UTC'}
deps = ['prettier']
run = """
rollup --config rollup/client.config.js
"""

[[task]]
name = 'prettier'
deps = [
  'client/**/*',
  'common/**/*'
]
run = """
prettier \
  --loglevel warn \
  --cache \
  --cache-strategy metadata \
  --ignore-path ../.prettierignore \
  --write "client/**/*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)" \
  --write "common/**/*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)" \
  --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql)" \
  --write "loaders/**/*.js" \
  --write "rollup/**/*.js" \
  --write "./*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)"
"""


[[task]]
name = 'clear-cache'
run = '''
rimraf node.importmap
rimraf .cache
rimraf .ssr
'''

############################# 
#############################
#############################

[[task]]
name = 'reset'
run = """
rm -rf node_modules
find . \
  -name node_modules \
  -type d \
  -exec rm -rv {} + \
    && find . \
      -name package-lock.json \
      -type f \
      -delete
"""