version = 0.1
default-task = 'start'
extensions = ['chomp@0.1:jspm']

############################# 
#############################
#############################

[[task]]
name = 'start'
serial = true
deps = ['reset-cache', 'client', 'server']

############################# 
#############################
#############################

[[task]]
name = 'server'
env = { TZ='UTC', NODE_ENV='development' }
run = """
nodemon \
  --watch node.importmap \
  --watch server/ \
  --watch loaders/ \
  --watch .cache/ \
  --watch loader/ \
  --ignore server/ssr/*.js \
  --exec \
    'prettier \
      --ignore-path ../.prettierignore \
      --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql)" \
      --write "loaders/**/*.js" && \
    rollup --config rollup.server.config.js && \
    NODE_LOADER_CONFIG=loaders/config.js \
      node \
        --trace-warnings \
        --experimental-loader @node-loader/core \
        server'
"""

############################# 
#############################
#############################

[[task]]
name = 'client'
serial = true
deps = ['rollup:client', 'jspm']

############################# 
#############################
#############################

[[task]]
name = 'jspm'
deps = ['jspm:client', 'jspm:node']

# Create an import map for node
[[task]]
name = 'jspm:node'
dep = 'server/index.importmap.js'
target = 'node.importmap'
template = 'jspm'
[task.template-options]
default-provider = 'jspm'
env = ['node', 'development', 'module']

# Transpile HTML + js => HTML / import map
[[task]]
name = 'jspm:client'
dep = 'client/html/#.html'
target = '.cache/#.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'development', 'module']
default-provider = 'jspm'
preload = true
integrity = false

# Then transpile client code to ES5
[[task]]
name = 'rollup:client'
dep = 'client/##.js'
run = 'rollup --config rollup.client.config.js'

# First delete and recreate the cache
[[task]]
name = 'reset-cache'
run = """
rimraf node.importmap
rimraf .cache
mkdir .cache
"""

############################# 
#############################
#############################

[[task]]
name = 'prettier'
run = """
prettier \
  --ignore-path ../.prettierignore \
  --write "client/**/*.@(js|jsx|json|mjs|cjs|graphql|yml)" \
  --write "loaders/*.js" \
  --write "./*.@(js|jsx|json|mjs|cjs|graphql|yml)"
"""

# DEPENDENCY MANAGEMNT

[[task]]
name = 'clean-deps'
run = 'find . -name node_modules -type d -exec rm -rv {} + && find . -name package-lock.json -type f -delete'

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = """
ncu -u
npm install
"""

