version = 0.1
default-task = 'start'
extensions = ['chomp@0.1:jspm']

############################# 
#############################
#############################

[[task]]
name = 'start'
serial = true
deps = ['reset-cache', 'clients', 'server']

[[task]]
name = 'server'
env = { TZ='UTC' }
run = """
nodemon --watch server/ --exec \
  'prettier --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql)" && \
   node --trace-warnings --loader ./loaders/geojson.js --experimental-json-modules server'
"""

[[task]]
name = 'clients'
serial = true
deps = ['rollup', 'html']

[[task]]
name = 'html'
dep = 'clients/html/#.html'
target = '.cache/#.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'production', 'module']
preload = true
integrity = false

[[task]]
name = 'rollup'
dep = 'clients/##.js'
run = 'rollup --config rollup.config.js'

[[task]]
name = 'reset-cache'
run = """
rimraf .cache
mkdir .cache
"""

############################# 
#############################
#############################

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = """
ncu -u
npm install
"""

[[task]]
name = 'prettier'
run = 'prettier --write "./**/*.@(js|jsx|json|mjs|cjs|graphql|yml)"'