version = 0.1
default-task = 'start'
extensions = ['chomp@0.1:jspm', 'chomp@0.1:swc']

############################# 
#############################
#############################

[[task]]
name = 'start'
serial = true
deps = ['.cache', '.cache/*.html', 'server']

############################# 
#############################
#############################

[[task]]
name = 'server'
env = { TZ='UTC', NODE_ENV='development', NODE_LOADER_CONFIG='loaders/config.js' }
serial = true
deps = ['server/ssr/index.js', 'node.importmap']
run = """
prettier \
  --ignore-path ../.prettierignore \
  --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql)" \
  --write "loaders/**/*.js"
node --trace-warnings --experimental-loader @node-loader/core server
"""

[[task]]
target = 'server/ssr/index.js'
dep = 'server/ssr/src/index.js'
run = 'rollup -c rollup/server.config.js'

############################# 
#############################
#############################

# Create an import map for node
[[task]]
name = 'jspm:node'
deps = ['index.importmap.js', '.cache']
target = 'node.importmap'
template = 'jspm'
[task.template-options]
default-provider = 'jspm'
env = ['node', 'development', 'module']
ignore = [
  'graphql',
  'apollo-server-core',
  'apollo-server-koa',
  'koa-bodyparser'
]

# Transpile HTML + js => HTML / import map
[[task]]
name = 'jspm:client'
deps = ['client/html/#.html', '.cache']
target = '.cache/#.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'development', 'module']
default-provider = 'jspm'
preload = true
integrity = false

[[task]]
target = '.cache'
dep = 'client/**/*.js'
run = """
rollup --config rollup/client.config.js
"""

# First delete and recreate the cache
[[task]]
name = 'clear-cache'
run = """
rimraf node.importmap
rimraf .cache
rimraf server/ssr/*.js
"""

############################# 
#############################
#############################

# [[task]]
# name = 'prettier'
# dep = 'client/**/*.js'
# run = 'prettier --ignore-path ../.prettierignore --write "${{changed}}"'

[[task]]
name = 'prettier'
run = """
prettier \
  --ignore-path ../.prettierignore \
  --write "client/**/*.@(js|jsx|json|mjs|cjs|graphql|yml)" \
  --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql)" \
  --write "loaders/**/*.js" \
  --write "./*.@(js|jsx|json|mjs|cjs|graphql|yml)"
"""

# DEPENDENCY MANAGEMNT

[[task]]
name = 'clean-deps'
run = 'find . -name node_modules -type d -exec rm -rv {} + && find . -name package-lock.json -type f -delete'

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = """
ncu -u
npm install
"""

