version = 0.1
default-task = 'start'
extensions = ['chomp@0.1:jspm', 'chomp@0.1:swc']

############################# 
#############################
#############################

[[task]]
name = 'start'
deps = ['client', 'server']

############################# 
#############################
#############################

[[task]]
name = 'server'
env = { TZ='UTC', NODE_ENV='development', NODE_LOADER_CONFIG='loaders/config.js' }
deps = ['server/ssr/index.js', 'prettier']
run = 'node --trace-warnings --experimental-loader @node-loader/core server'

[[task]]
target = 'server/ssr/index.js'
dep = 'server/ssr/src/index.js'
run = 'rollup -c rollup.server.config.js'

############################# 
#############################
#############################

[[task]]
name = 'client'
deps = ['.cache', '.cache/*.html', 'node.importmap']

############################# 
#############################
#############################

# Create an import map for node
[[task]]
name = 'jspm:node'
deps = ['index.importmap.js', '.cache']
target = 'node.importmap'
template = 'jspm'
[task.template-options]
default-provider = 'jspm'
env = ['node', 'development', 'module']

# Transpile HTML + js => HTML / import map
[[task]]
name = 'jspm:client'
deps = ['client/html/#.html', '.cache']
target = '.cache/#.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'development', 'module']
default-provider = 'jspm'
preload = true
integrity = false

# Then transpile client code to ES5
[[task]]
target = '.cache'
dep = 'client/**/*.js'
run = 'rollup --config rollup.client.config.js'

[[task]]
dep = 'client/pages/#/index.js'
target = 'client/pages/#/.cache/index.js'
template = 'swc'

# First delete and recreate the cache
[[task]]
name = 'clear-cache'
run = """
rimraf node.importmap
rimraf .cache
"""

############################# 
#############################
#############################

[[task]]
name = 'prettier'
run = """
prettier \
  --ignore-path ../.prettierignore \
  --write "client/**/*.@(js|jsx|json|mjs|cjs|graphql|yml)" \
  --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql)" \
  --write "loaders/**/*.js" \
  --write "./*.@(js|jsx|json|mjs|cjs|graphql|yml)"
"""

# DEPENDENCY MANAGEMNT

[[task]]
name = 'clean-deps'
run = 'find . -name node_modules -type d -exec rm -rv {} + && find . -name package-lock.json -type f -delete'

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = """
ncu -u
npm install
"""

