version = 0.1
default-task = 'start'

extensions = ['chomp@0.1:jspm']

[[task]]
name = 'start'
serial = true
deps = ['client', 'server',]

[[task]]
name = 'server'
env = { TZ='UTC' }
run = """
nodemon --watch server/ --exec \
  'prettier --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql)" && \
   node --trace-warnings --loader ./loaders/geojson.js --experimental-json-modules server'
"""

[[task]]
name = 'client'
serial = true
deps = ['build:js', 'jspm']

[[task]]
name = 'build:js'
dep = 'clients/##'
run = 'swc clients -d server/ssr/dist'

[[task]]
name = 'jspm'
dep = 'clients/pages/#/index.html'
target = 'server/ssr/dist/pages/#/index.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'production', 'module']
preload = true
integrity = false

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = """
ncu -u
npm install
"""