version = 0.1
default-task = 'start'

[[task]]
name = 'start'
deps = [
    '.cache',
    '.cache/*.html',
    'copy-static-files',
    'server',
]
serial = true

#############################
#############################
#############################

[[task]]
name = 'copy-static-files'
run = '''
cp -r public/* .cache/
'''

[[task]]
name = 'server'
env = { TZ='UTC', NODE_LOADER_CONFIG='loaders/config.js' }
serial = true
deps = [
  'rollup:ssr',
  'node.importmap',
  'server/**/*.js',
]
run = """
prettier \
  --loglevel warn \
  --cache \
  --cache-strategy metadata \
  --ignore-path ../.prettierignore \
  --write "ssr/**/*.@(js|json|geojson|cjs|mjs|graphql|ts|tsx|jsx)" \
  --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql|ts|tsx|jsx)" \
  --write "loaders/**/*.js" && \
    node \
      --trace-warnings \
      --loader @node-loader/core \
      server
"""

[[task]]
name = 'rollup:ssr'
deps = ['ssr/**/*.jsx']
env = { TZ='UTC' }
run = 'rollup -c rollup/server.config.js'

############################# 
#############################
#############################

# Create an import map for node
[[task]]
name = 'jspm:node'
targets = ['node.importmap']
deps = [
    'index.importmap.js',
    '.cache'
]
invalidation = 'always'
run = "node jspm-node.js"

# Transpile HTML + js => HTML / import map
[[task]]
name = 'jspm:client'
targets = ['.cache/#.html']
deps = [
    'client/html/#.html',
    '.cache'
]
invalidation = 'always'
run = "node jspm-client.js"

[[task]]
target = '.cache'
deps = [
  'client/**/*',
  'common/**/*'
]
env = { TZ='UTC'}
run = """
prettier \
  --loglevel warn \
  --cache \
  --cache-strategy metadata \
  --ignore-path ../.prettierignore \
  --write "client/**/*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)" \
  --write "common/**/*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)" \
  && rollup \
    --config rollup/client.config.js
"""

[[task]]
name = 'clear-cache'
run = '''
rimraf node.importmap
rimraf .cache
rimraf .ssr
'''

############################# 
#############################
#############################


[[task]]
name = 'prettier'
run = """
prettier \
  --cache \
  --cache-strategy metadata \
  --ignore-path ../.prettierignore \
  --write "client/**/*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)" \
  --write "common/**/*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)" \
  --write "server/**/*.@(js|json|geojson|cjs|mjs|graphql)" \
  --write "loaders/**/*.js" \
  --write "rollup/**/*.js" \
  --write "./*.@(js|jsx|json|mjs|cjs|graphql|yml|ts|tsx)"
"""

[[task]]
name = 'reset'
run = 'find . -name node_modules -type d -exec rm -rv {} + && find . -name package-lock.json -type f -delete'

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = '''
ncu -u
npm install
'''
